export const BLOG_POSTS = [
  {
    slug: "why-your-restaurant-needs-a-website",
    cat: "WEBSITE TIPS",
    title: "Why Your Restaurant Needs a Website in 2026 (Not Just a Zomato Page)",
    time: "4 min",
    date: "Mar 20, 2026",
    author: "Naisora Team",
    image: "/projects/mockup1.png",
  },
  {
    slug: "how-to-rank-on-google-maps",
    cat: "GOOGLE SEO",
    title: "How to Rank #1 on Google Maps for 'Restaurants Near Me' in Bangalore",
    time: "6 min",
    date: "Mar 15, 2026",
    author: "Naisora Team",
    image: "/projects/mockup2.png",
  },
  {
    slug: "ai-whatsapp-automation",
    cat: "AUTOMATION",
    title: "How AI Can Reply to Your WhatsApp Orders While You're Cooking",
    time: "5 min",
    date: "Mar 10, 2026",
    author: "Naisora Team",
    image: "/projects/mockup3.png",
  },
  {
    slug: "restaurant-website-essentials",
    cat: "WEBSITE TIPS",
    title: "The 7 Things Every Restaurant Website Must Have to Convert Visitors",
    time: "7 min",
    date: "Mar 05, 2026",
    author: "Naisora Team",
    image: "/projects/mockup4.png",
  },
  {
    slug: "restaurant-logo-matters",
    cat: "BRANDING",
    title: "Why Your Restaurant Logo Matters More Than You Think",
    time: "3 min",
    date: "Feb 28, 2026",
    author: "Naisora Team",
    image: "/projects/mockup2.png",
  },
  {
    slug: "competitor-not-on-google",
    cat: "GOOGLE SEO",
    title: "Competitor Not on Google? Here's How to Capture Their Customers",
    time: "5 min",
    date: "Feb 20, 2026",
    author: "Naisora Team",
    image: "/projects/mockup3.png",
  },
  {
    slug: "spice-garden-case-study",
    cat: "SUCCESS STORY",
    title: "Case Study: How Spice Garden Got 40% More Direct Orders in 30 Days",
    time: "8 min",
    date: "Mar 22, 2026",
    author: "Naisora Team",
    image: "/projects/mockup1.png",
  },
  {
    slug: "hidden-cost-delivery-apps",
    cat: "BUSINESS",
    title: "The Hidden Cost of Relying on Food Delivery Apps — And How to Fix It",
    time: "6 min",
    date: "Mar 15, 2026",
    author: "Naisora Team",
    image: "/projects/mockup2.png",
  },
];
